# Generated by Django 4.2.1 on 2023-05-05 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('rbd', models.IntegerField(primary_key=True, serialize=False)),
                ('digito_verificador', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('patente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('oferente', models.CharField(max_length=100)),
                ('cantidad_km', models.FloatField()),
                ('alumnos', models.PositiveIntegerField()),
                ('sectores', models.CharField(max_length=200)),
                ('url_mapa', models.URLField(blank=True, null=True)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.escuela')),
            ],
        ),
    ]
